version: "3"

services:
    php:
        image: thecodingmachine/php:7.4-v4-cli
        volumes:
            - .:/application
        working_dir: "/application"
        environment:
            PHP_EXTENSION_XDEBUG: 1
            PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
